# Generated by Django 4.2.4 on 2023-09-01 09:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Team",
            new_name="TeamModel",
        ),
    ]
