# Generated by Django 4.2.4 on 2023-09-08 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_rename_team_teammodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TeamModel",
            new_name="Team",
        ),
    ]
