# Generated by Django 4.2.4 on 2023-09-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=50)),
                ("subject", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
