# Generated by Django 4.2.4 on 2023-09-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Society",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(max_length=150)),
                ("logo", models.ImageField(upload_to="images/society/")),
                ("slug", models.SlugField(editable=False, max_length=100)),
            ],
            options={
                "verbose_name_plural": "Societies",
            },
        ),
    ]
